sub EVENT_SAY {
  if ($text=~/hail/i) {
    quest::say("You stand before Charayan, Crusader of Veeshan. I am the talon that justly strikes down our enemies and shall fulfill our destiny in the trials of blood and vengeance. I sense that the loyalty you bear toward the children of scale is strong but the siren voice that has called you to us is still a whisper upon your mind, and it is a song of curiosity and greed that fuels you yet. Since the dawn of your creation, all of your kind has proven that without tangible reward to do otherwise, your blades would be aimed for our hearts. But do not think we fault you for merely this -- such shallow lusts have become a definition of your kind, and we do not bear you ill will for it. However, the [champions] are not as the others of Veeshan's brood and your past deeds shall [not bear fruitful] in your dealings with us.");
  }
  if ($text=~/champions/i) {
  quest::emote("Charayan the Crusader rears upon her hind legs and extends her wings once more in a glorious display");
    quest::say("The Crusaders of Veeshan are four champions of dragon kind who have dedicated their very lives to the restoration of Kerafyrm's slumber and undoing that which your kind has so ignorantly threatened this world with. Fate has given room for nothing short of this declaration and the recent past has demanded our attention and duty to be thus. Your kind, the second generation, has carelessly shifted the destiny of all upon this world and it is your ignorant and lustful actions that have forced us into existence as we are now. Kerafyrm, the Sleeper, was well guarded for all these years not without dire justification -- he cannot be destroyed by means conceivable by dragon or second generation alike. We are those whose existence is to combat this shadow and [keep it at bay], despite all costs and with all sacrifice.");
  }
  if ($text=~/keep it at bay/i) {
    quest::say("When Kerafyrm was first recognized as a dire threat to this world, the four Warders were chosen. The elders of the council knew that time's grace upon us was thin and that the warders must be recognized as a temporary means of subduing this threat. Before the great war that would yield Kerafyrm's incarceration, the warders were instructed to mate with four dragons of pure elements as their. The offspring of these unions would be trained for the undivided purpose of fulfilling their predecessors' duties when their fate would inevitably dawn. However, your kind have forced the apprentices into a [new role], one that we had not anticipated, but such was our mistake to overestimate and consider your kind the ability to rise above your debased natures and shallow existence.");
  }
  if ($text=~/new role/i) {
    quest::say("When Kerafyrm was awoken, the apprentices were called by the council to prepare for the hunt and his recapture. The apprentices were not as agreeable to the council's plan as they had anticipated and the Crusaders were born of our own accord. For months the deliberations and cordial arguments raged, but all that would eventually come would be the unspoken disapproval of the council and the apprentices' self-imposed adoption of a new and more necessary duty. We have come to Skyshrine to fulfill our purpose, but those passing months ushered in an unseen darkness that the Crusaders had feared from the first movement of Kerafyrm's eye -- the [ancients] returned.");
  }
  if ($text=~/ancients/i) {
  quest::emote("Charayan the Crusader gives another bellowing roar, her wings flaring outward in an intimidating and almost frightful display");
    quest::say("The Ancients are not to be trifled with, although your kind will find your just retribution upon their fiery talons if we, the Crusaders, cannot undo your ignorance. You ask for their [names, for their past and for their meaning] to this perilous path that you have set us upon, and your actions have earned you nothing less than the obligation to know the fullest extent of what you have unleashed upon this world. But do not take these words lightly, nor think yourself a hero standing in the fading shadow of a great monster. Although those of you whom still bear allegiance to the Claws of Veeshan will be demanded by the Crusaders to engage these monstrosities of Veeshan's brood, you shall gain neither repute nor true victory if you succeed in such a task.");
  }
  if ($text=~/names/i) {
  quest::say("When Kerafyrm had proven his mad, relentless nature, the elder council of the Claws of Veeshan ordered Kerafyrm's destruction as an absolute necessity to escape existence as slaves to the tyranny of a mad abomination. During this time, Kerafyrm had established allies within the Velious nation -- amongst these allies were four elders upon the very council that sought to destroy him. Kildrukaun, the former Arch Priest of Veeshan and driving force behind the decree that forbade the existence of creatures such as Kerafyrm was the first to betray the Claws of Veeshan. Vyskudra, the magnificent dragon of the storms followed the lead of her patron and master. Third was Tjudawos, the scholar of the council. Lastly was Zeixshi-Kar, the general who engaged within the fledgling war with the giants of Kael that would last for centuries beyond her departure. These four elders would become the driving force behind Kerafyrm's army and are now the [greatest danger] we face in the current era of this turmoil.");
   }
   if ($text=~/greatest danger/i) {
     quest::say("No longer are these great dragons merely elders, for they have ascended to a place within dragon hierarchy that has been done so rarely -- they have become ancients; powerful immortals whose essence lies beyond our realm and reach. These creatures are beyond anything you have faced in your lifetime -- beyond the pitiable creatures of your lesser deities' planes and beyond anything that the horde of your entire existence could comprehend. These ancients, these immortal creatures of pure destruction, chaos, and envenomed hate are the key to Kerafyrm's fullest potential. This is why they must be [hindered] from manifesting the fullest of their power as they lay in wait for their master's return.");
   }
   if ($text=~/hinder/i) {
     quest::say("Do not be so quick to presume that those as ignorant, shallow, and debased as the second generation could create even the slightest ripple in the waters that you yourself have unleashed. An entire army of Veeshan's most powerful brood was unable to destroy these creatures, so do not think that you of the second generation could stride beyond that which we could not. But do not be discouraged, for the second generation is not so easily with excuse to walk away from this threat, for as the children of scale are in danger, your kind will suffer a thousand fold if Kerafyrm and his ancient minions are successful. The ancients are powerful immortals indeed, but their forms lie on the primal world and thus they are subject to its laws, however vain they ultimately prove to be. If you are able to engage the Ancients and survive, temporarily extinguishing their corporeal form, you would have completed a great feat that would [hold no permanent impact] on our struggle.");
   }
   if ($text=~/permanent impact/i) {
     quest::say("As the Ancients may be subject to the laws of the primal world, their essence and consciousness remain truly immortal. Once their physical manifestations have been extinguished, it is only a matter of time before they coalesce and return to whatever malevolent course of action that they are undoubtedly paving. Undoubtedly, you and your kind will seek glory, wealth and fame within Kerafyrm's former place of imprisonment and the Ancients will be upon the end goals for all that enter. I will not discourage you or your kind from such a course of action -- for your lives are your lives alone to endanger and discard as you wish. However, if those of your kind whom remain loyal to the Claws of Veeshan are [of the mind to engage in such a battle] and if the fates extend their pity upon you, then perhaps you shall be of aid to us yet.");
   }
   if ($text=~/battle/i) {
     quest::say("We shall not place dire importance upon your return. The venture will be difficult and you shall likely fail if not by your own fallible entireties, then by the overwhelming might of the Ancients. If you confront the Ancients and if you are successful, specific samples from their corporeal forms would be of limitless use to us in our endeavors to keep Kerafyrm and his minions at bay, if not permanently extinguished. For our efforts to be of any due worth, we need one sample from each dragon, and each Crusader must be given the particular representation of their duty by one whose spirit and disciplines are paralleled. If you are a warrior among your kind -- one who wields steel in battle for reasons of either faith, honor, or repute among your shallow little world, mind that I care nothing for what your kind deem as dark or corrupt for the soldiers upon a battlefield are all fundamentally identical in their foundation, then I shall ask that you return your [findings] to me.");
   }
   if ($text=~/findings/i) {
     quest::say("Only one whose spirit is saturated with the stains of countless battles can extract the primal claws of these temporary manifestations. One claw from each of the Ancients is necessary for this task to be complete. If you are so fortunate as to recover one of these precious items from each of the ancients, you are to return them to me, but only when and if you acquire the four separate claws. However, be warned that the Ancient's forms are unpredictable and we are not certain what will remain intact once their essence and consciousness have fled their forms and you may find yourself standing before the lifeless form of a monstrous behemoth, but the mighty claw you seek may be too damaged or deteriorated from the sudden loss of its life-giving essence.");
   }
}

sub EVENT_ITEM {
  if (plugin::check_handin(\%itemcount, 9347 => 1, 9349 => 1, 9348 => 1, 9409 => 1)) {
 quest::say("You cannot fathom the importance of your actions, $name. What you have accomplished cannot be claimed in truth by many and know that all sacrifices that you and those who have undoubtedly aided you have made in fulfilling this awesome feat shall not go without notice. The Crusaders of Veeshan can express neither the prominent magnitude of the honor that you have upheld in maintaining your convictions to the Claws of Veeshan. We, the Crusaders of Veeshan, honor you, $name of the second generation. Within this ring you shall find a single stone of ever changing chromatic essence -- the very essence of the first chromatic nobles deposited by Veeshan's great claw. Take it not as a gift nor as restitution for your deeds, but take it as a token of acknowledgement and a symbol of your proven significance within the boundless realm of our crusade."); 
 quest::summonitem(30388);  
  }
}

