--npc to start quest for access to locked library door

function event_say(e)
	if(e.message:findi("hail")) then
		e.self:Say("'Oh mighty master, please spare me from needless intrusions. Did [they] send you to ask me some foolish question about where your quarters are or whose boot you need to lick to get access to a chamber pot?'");
	elseif(e.message:findi("they")) then
		e.self:Say(" 'Did they also send you to further their attempts to drive me completely mad? Me, Magnificent Melion, once master of Erudin in all but title, trapped here to tend to the needs of wet-behind-the-ears visitors.' Melion sighs. 'Fine. I will once again be forced to prove that my powers of deduction are still brilliant. You are certainly not a long-term visitor here or you would not be bothering me at all. You are not an invader because you have not tried to kill me. So you must be one of those that have been brought here to satisfy their desires to know everything about everything. It's been a long time since they've had any new information from the daylight and they must be hungry for it. That seems to be the reason people come here, they have some sort of [hunger].'");
	elseif(e.message:findi("hunger")) then
		e.self:Say("'They have it. I had it. The Master has it. I hungered for control. The Quartet hunger for knowledge, or what they think of as knowledge. The Master, well I won't claim to speak about him. I wasn't happy administering all of Erudin from behind the curtains, so when one of the Quartet came to me and offered me a chance to run the greatest library in the world with opportunity to run the daily activities of the greatest being to ever live, I accepted with greed. I knew that I would succeed. Of course I was a fool. I assumed that what the Quartet wanted was someone capable. It turns out that they just wanted a scribe and lackey. They wanted the best scribe and lackey on Norrath. Of course at first I thought I could supplant them once their superiors noticed my skill. After decades of trying to attain my rightful place here I have grown weary and they have assigned me the stupidest [tasks] they can find.'");
	elseif(e.message:findi("task")) then
		e.self:Say(" 'Hah!' Melion raises his voice in a single sharp syllable that bounces around the elegant hall. 'The things they make me do aren't worthy of me. They might be worthy of someone like you, but even you would refuse to do them.' You see Melion look you over with an evaluating glare. He continues his speech with his voice lowered nearly to a whisper. 'Perhaps I overestimate you. It lowers my station every time I am seen doing these menial tasks, but you have no station here at all. You could do these chores for me and I could give you some information that you might need. I have fallen far, perhaps, but I have not forgotten everything that I learned. Will you do menial work in exchange for knowledge? You appear to be the [purchasable] type.'");
	elseif(e.message:findi("purchasable")) then
		e.self:Say(" 'Good to hear it. Some have made their way up the ladder in this place by simply pleasing those of higher station. You might be one of that type. If so this will be the first rung on that ladder for you. I warn you, though, that with my chores does not come my authority, such as it is. You will have to find your own way in this place and deal with the other occupants in whatever way you see fit. The only rule is that you must not tell them that I sent you. If you do, all reward will be lost to you.'");
    e.other:AssignTask(505745,e.self:GetID());
	end
end
